//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealPlannerClient.App.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MealPlannerClient.App.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Recipe.
        /// </summary>
        internal static string AddRecipe {
            get {
                return ResourceManager.GetString("AddRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products were not found.
        /// </summary>
        internal static string AvailableProductsEmpty {
            get {
                return ResourceManager.GetString("AvailableProductsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available products are loading....
        /// </summary>
        internal static string AvailableProductsLoading {
            get {
                return ResourceManager.GetString("AvailableProductsLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available products.
        /// </summary>
        internal static string AvailableProductsText {
            get {
                return ResourceManager.GetString("AvailableProductsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Recipe.
        /// </summary>
        internal static string CreateNewRecipeHeader {
            get {
                return ResourceManager.GetString("CreateNewRecipeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a number.
        /// </summary>
        internal static string EnterNumber {
            get {
                return ResourceManager.GetString("EnterNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while deleting recipe!.
        /// </summary>
        internal static string ErrorDeletingRecipe {
            get {
                return ResourceManager.GetString("ErrorDeletingRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while loading recipes!.
        /// </summary>
        internal static string ErrorLoadingRecipe {
            get {
                return ResourceManager.GetString("ErrorLoadingRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while saving recipe!.
        /// </summary>
        internal static string ErrorSavingRecipe {
            get {
                return ResourceManager.GetString("ErrorSavingRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to g.
        /// </summary>
        internal static string Gram {
            get {
                return ResourceManager.GetString("Gram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your inventory is empty.
        /// </summary>
        internal static string InventoryEmpty {
            get {
                return ResourceManager.GetString("InventoryEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your inventory is loading....
        /// </summary>
        internal static string InventoryLoading {
            get {
                return ResourceManager.GetString("InventoryLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string LeavePageWithUnsavedChangesAlertNoOption {
            get {
                return ResourceManager.GetString("LeavePageWithUnsavedChangesAlertNoOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There some unsaved changes. Leaving the page will revert them. Are you sure?.
        /// </summary>
        internal static string LeavePageWithUnsavedChangesAlertText {
            get {
                return ResourceManager.GetString("LeavePageWithUnsavedChangesAlertText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string LeavePageWithUnsavedChangesAlertTitle {
            get {
                return ResourceManager.GetString("LeavePageWithUnsavedChangesAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string LeavePageWithUnsavedChangesAlertYesOption {
            get {
                return ResourceManager.GetString("LeavePageWithUnsavedChangesAlertYesOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mL.
        /// </summary>
        internal static string Milliliter {
            get {
                return ResourceManager.GetString("Milliliter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute(s).
        /// </summary>
        internal static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory already contains this product.
        /// </summary>
        internal static string MyProductAlreadyExists {
            get {
                return ResourceManager.GetString("MyProductAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes saved!.
        /// </summary>
        internal static string MyProductsSaved {
            get {
                return ResourceManager.GetString("MyProductsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Products.
        /// </summary>
        internal static string MyProductsText {
            get {
                return ResourceManager.GetString("MyProductsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Recipes.
        /// </summary>
        internal static string MyRecipesText {
            get {
                return ResourceManager.GetString("MyRecipesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        internal static string PagerPage {
            get {
                return ResourceManager.GetString("PagerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        internal static string PagerPageOf {
            get {
                return ResourceManager.GetString("PagerPageOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cook Time (minutes).
        /// </summary>
        internal static string RecipeCookTimeMinutesLabel {
            get {
                return ResourceManager.GetString("RecipeCookTimeMinutesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe successfully deleted!.
        /// </summary>
        internal static string RecipeDeleted {
            get {
                return ResourceManager.GetString("RecipeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredients.
        /// </summary>
        internal static string RecipeIngredientsLabel {
            get {
                return ResourceManager.GetString("RecipeIngredientsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions.
        /// </summary>
        internal static string RecipeInstructionsLabel {
            get {
                return ResourceManager.GetString("RecipeInstructionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string RecipeNameLabel {
            get {
                return ResourceManager.GetString("RecipeNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparation Steps.
        /// </summary>
        internal static string RecipePreparationStepsLabel {
            get {
                return ResourceManager.GetString("RecipePreparationStepsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe successfully saved!.
        /// </summary>
        internal static string RecipeSaved {
            get {
                return ResourceManager.GetString("RecipeSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You didn&apos;t save any recipes yet.
        /// </summary>
        internal static string RecipesEmpty {
            get {
                return ResourceManager.GetString("RecipesEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipes are loading....
        /// </summary>
        internal static string RecipesLoading {
            get {
                return ResourceManager.GetString("RecipesLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipes are saving....
        /// </summary>
        internal static string RecipesSaving {
            get {
                return ResourceManager.GetString("RecipesSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveButtonText {
            get {
                return ResourceManager.GetString("SaveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type name of the product....
        /// </summary>
        internal static string SearchBarPlaceholder {
            get {
                return ResourceManager.GetString("SearchBarPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Big.
        /// </summary>
        internal static string Settings_BigFont {
            get {
                return ResourceManager.GetString("Settings_BigFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Theme.
        /// </summary>
        internal static string Settings_ColorTheme {
            get {
                return ResourceManager.GetString("Settings_ColorTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Size.
        /// </summary>
        internal static string Settings_FontSize {
            get {
                return ResourceManager.GetString("Settings_FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string Settings_MidFont {
            get {
                return ResourceManager.GetString("Settings_MidFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small.
        /// </summary>
        internal static string Settings_SmallFont {
            get {
                return ResourceManager.GetString("Settings_SmallFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI Copilot.
        /// </summary>
        internal static string SideMenu_Copilot {
            get {
                return ResourceManager.GetString("SideMenu_Copilot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        internal static string SideMenu_Inventory {
            get {
                return ResourceManager.GetString("SideMenu_Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Recipes.
        /// </summary>
        internal static string SideMenu_Recipes {
            get {
                return ResourceManager.GetString("SideMenu_Recipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SideMenu_Settings {
            get {
                return ResourceManager.GetString("SideMenu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item(s).
        /// </summary>
        internal static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
    }
}
